//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MContracts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MContracts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление договорами.
        /// </summary>
        internal static string AppTitleString {
            get {
                return ResourceManager.GetString("AppTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр договоров.
        /// </summary>
        internal static string ContractRepositoryString {
            get {
                return ResourceManager.GetString("ContractRepositoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на от.
        /// </summary>
        internal static string FromStrign {
            get {
                return ResourceManager.GetString("FromStrign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый договор.
        /// </summary>
        internal static string NewContractString {
            get {
                return ResourceManager.GetString("NewContractString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (без номера).
        /// </summary>
        internal static string NoNumString {
            get {
                return ResourceManager.GetString("NoNumString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестры.
        /// </summary>
        internal static string RepositoriesString {
            get {
                return ResourceManager.GetString("RepositoriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению произошла ошибка при сохранении результатов вашей работы. Сообщение об ошибке: {0} Эта проблема не должна проявляться в системе. Следует сообщить о проблеме разработчикам системы, приложив журнал работы. Также попробуйте выполнить следующие действия: 1) Повторите последнюю операцию. 2) Закройте вкладку рабочей области на которой произошла ошибка и откроойте снова. 3) Повторно внесите данные и сохраните результат..
        /// </summary>
        internal static string SaveWorkspaceFailed {
            get {
                return ResourceManager.GetString("SaveWorkspaceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению произошла ошибка при сохранении результатов вашей работы. Сообщение об ошибке: .
        /// </summary>
        internal static string SaveWorkspaceFailed1 {
            get {
                return ResourceManager.GetString("SaveWorkspaceFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление статистики....
        /// </summary>
        internal static string UpdateStatisticsBusyContent {
            get {
                return ResourceManager.GetString("UpdateStatisticsBusyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление статистики завершено. Не забудьте перезапустить приложение перед продолжением работы..
        /// </summary>
        internal static string UpdateStatisticsFinishedWarning {
            get {
                return ResourceManager.GetString("UpdateStatisticsFinishedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление статистики включает пересчёт сумм по выполнению этапов договоров и может занять некоторое время, в зависимости от объёма данных в системе. Обычно, пересчёт происходит автоматически при изменениях в данных. Если вы считаете, что суммы отображаются неправильно - воспользуйтесь этой функцией. По окончании процесса обновления потребуется перезапустить приложение. Желаете продолжить?.
        /// </summary>
        internal static string UpdateStatisticsWarning {
            get {
                return ResourceManager.GetString("UpdateStatisticsWarning", resourceCulture);
            }
        }
    }
}
