//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MContracts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RightPanelVisibility {
            get {
                return ((bool)(this["RightPanelVisibility"]));
            }
            set {
                this["RightPanelVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeftPanelVisibility {
            get {
                return ((bool)(this["LeftPanelVisibility"]));
            }
            set {
                this["LeftPanelVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Templates\\")]
        public string ReportTemplateFolder {
            get {
                return ((string)(this["ReportTemplateFolder"]));
            }
            set {
                this["ReportTemplateFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3_ContractQuarterInformation.xlt")]
        public string ContractPepiodInformationTemplate_3 {
            get {
                return ((string)(this["ContractPepiodInformationTemplate_3"]));
            }
            set {
                this["ContractPepiodInformationTemplate_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4_ContractQuarterPlanReport.xlt")]
        public string ContractQuarterPlanReport_4 {
            get {
                return ((string)(this["ContractQuarterPlanReport_4"]));
            }
            set {
                this["ContractQuarterPlanReport_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5_SubContractRegisterReport.xlt")]
        public string SubContractRegisterReport_5 {
            get {
                return ((string)(this["SubContractRegisterReport_5"]));
            }
            set {
                this["SubContractRegisterReport_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6_HandingWorkReport.xlt")]
        public string HandingWorkReport_6 {
            get {
                return ((string)(this["HandingWorkReport_6"]));
            }
            set {
                this["HandingWorkReport_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7_YearEfficientInformationReport.xlt")]
        public string YearEfficientInformationReport_7 {
            get {
                return ((string)(this["YearEfficientInformationReport_7"]));
            }
            set {
                this["YearEfficientInformationReport_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Act1.dot")]
        public string Act1Report {
            get {
                return ((string)(this["Act1Report"]));
            }
            set {
                this["Act1Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PageSize {
            get {
                return ((int)(this["PageSize"]));
            }
            set {
                this["PageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadInactiveContracts {
            get {
                return ((bool)(this["LoadInactiveContracts"]));
            }
            set {
                this["LoadInactiveContracts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float DefaultPrepaymentPercent {
            get {
                return ((float)(this["DefaultPrepaymentPercent"]));
            }
            set {
                this["DefaultPrepaymentPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2_ContractInformation.xlt")]
        public string ContractInformationTemplate_2 {
            get {
                return ((string)(this["ContractInformationTemplate_2"]));
            }
            set {
                this["ContractInformationTemplate_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1_YearPlanReport.xlt")]
        public string YearPlanReport_1 {
            get {
                return ((string)(this["YearPlanReport_1"]));
            }
            set {
                this["YearPlanReport_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InformationConcludedContracts.xlt")]
        public string InformationConcludedContracts {
            get {
                return ((string)(this["InformationConcludedContracts"]));
            }
            set {
                this["InformationConcludedContracts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkProgressReport.xlt")]
        public string WorkProgressReport {
            get {
                return ((string)(this["WorkProgressReport"]));
            }
            set {
                this["WorkProgressReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserReportFolder {
            get {
                return ((string)(this["UserReportFolder"]));
            }
            set {
                this["UserReportFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string MaxTabHeaderLength {
            get {
                return ((string)(this["MaxTabHeaderLength"]));
            }
            set {
                this["MaxTabHeaderLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Act2.dot")]
        public string Act2Report {
            get {
                return ((string)(this["Act2Report"]));
            }
            set {
                this["Act2Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Act3.dot")]
        public string Act3Report {
            get {
                return ((string)(this["Act3Report"]));
            }
            set {
                this["Act3Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Act4.dot")]
        public string Act4Report {
            get {
                return ((string)(this["Act4Report"]));
            }
            set {
                this["Act4Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NIOKRImplementationReport.xlt")]
        public string NIOKRImplementationReport {
            get {
                return ((string)(this["NIOKRImplementationReport"]));
            }
            set {
                this["NIOKRImplementationReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocumentDefFolder {
            get {
                return ((string)(this["DocumentDefFolder"]));
            }
            set {
                this["DocumentDefFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ContractInActionYearRegister.xlt")]
        public string ContractInActionYearRegister_1 {
            get {
                return ((string)(this["ContractInActionYearRegister_1"]));
            }
            set {
                this["ContractInActionYearRegister_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NIOKREconEfficiencyReport.xlt")]
        public string NIOKREconEfficiencyReport {
            get {
                return ((string)(this["NIOKREconEfficiencyReport"]));
            }
            set {
                this["NIOKREconEfficiencyReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TroubleNIOKRReport.xlt")]
        public string TroubleNIOKRReport {
            get {
                return ((string)(this["TroubleNIOKRReport"]));
            }
            set {
                this["TroubleNIOKRReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EconEffectNIOKRReport.xlt")]
        public string EconEffectNIOKRReport {
            get {
                return ((string)(this["EconEffectNIOKRReport"]));
            }
            set {
                this["EconEffectNIOKRReport"] = value;
            }
        }
    }
}
