/*
    UPDATE TO 1.0.0.14
*/
SELECT SYSDATE FROM DUAL;
ALTER TABLE WorkType ADD (ShortName NVARCHAR2(50) UNIQUE);
ALTER TABLE WorkType MODIFY Name NVARCHAR2(1000);
COMMENT ON COLUMN WorkType.ShortName IS 'Сокращённое название работ';

/*
    UPDATE PREPAYMENT COLUMNS PRECISION
*/

ALTER TABLE Contractdoc MODIFY PrepaymentSum NUMBER(18,2);
ALTER TABLE Prepayment MODIFY Sum NUMBER(18,2);
