-- This query will display the current date

/*UPDATE TO 1.49*/

SELECT SYSDATE FROM DUAL;
drop table CONTRACTDOCCONTRACTOR;
drop sequence  seq_CONTRACTDOCCONTRACTOR;

CREATE SEQUENCE seq_ContractorContractDoc START WITH 10000;
ALTER TABLE Document ADD FolderName nvarchar2(2000);
ALTER TABLE Document ADD Domain Number(10);

/*	ID	NAME	DOMAIN	FOLDERNAME
	1	Договор		
	3	Календарный план		
	4	Протокол цены		
	5	Лист согласования		
	6	Протокол разногласий		
	7	Протокол согласования разногласий		
	8	Письма		
	-1	(Не определён)		
	10000	Акт		
	9	Архив документов		
	10001	Сопутсвующие документы		
*/


UPDATE Document SET FolderName='Договор', Domain=1 WHERE Id=1 ;
UPDATE Document SET FolderName='Приложения', Domain=1 WHERE Id=3;
UPDATE Document SET FolderName='Сопровождение', Domain=1 WHERE Id=4;
UPDATE Document SET FolderName='Сопровождение', Domain=1 WHERE Id=5 ;
UPDATE Document SET FolderName='Сопровождение', Domain=1 WHERE Id=6 ;
UPDATE Document SET FolderName='Сопровождение', Domain=1 WHERE Id=7;
UPDATE Document SET FolderName='Сопровождение', Domain=1 WHERE Id=8;
UPDATE Document SET FolderName='Разное', Domain=0 WHERE Id=9;
UPDATE Document SET FolderName='Разное', Domain=0 WHERE Id=10001;
UPDATE Document SET FolderName='Акты', Domain=2 WHERE Id=10000;



ALTER TABLE Act DROP CONSTRAINT FKAct413802;
ALTER TABLE Act ADD CONSTRAINT FKAct413802 FOREIGN KEY (RegionID) REFERENCES Region (ID);
ALTER TABLE Act DROP CONSTRAINT FKAct287724; 
ALTER TABLE Act ADD CONSTRAINT FKAct287724 FOREIGN KEY (NDSID) REFERENCES NDS (ID);
ALTER TABLE Act DROP CONSTRAINT FKAct228252;
ALTER TABLE Act ADD CONSTRAINT FKAct228252 FOREIGN KEY (EnterpriceAuthorityID) references EnterpriseAuthority(ID);
ALTER TABLE ActPaymentDocument DROP CONSTRAINT FKActPayment244981; 
ALTER TABLE ActPaymentDocument ADD CONSTRAINT FKActPayment244981 FOREIGN KEY (PaymentDocumentID) REFERENCES PaymentDocument (ID) ON DELETE CASCADE;
ALTER TABLE ApprovalProcess DROP CONSTRAINT APPROVALPROCESS_STATE_FK;
ALTER TABLE ApprovalProcess ADD CONSTRAINT APPROVALPROCESS_STATE_FK FOREIGN KEY (ApprovalStateID) REFERENCES ApprovalState (ID);

ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo331897;
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo331897 FOREIGN KEY (ContractTypeID) REFERENCES ContractType (ID);
ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo465214;
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo465214 FOREIGN KEY (CurrencyID) REFERENCES Currency (ID);
ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo12114; 
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo12114 FOREIGN KEY (NDSAlgorithmID) REFERENCES NDSAlgorithm (ID);
ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo371687; 
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo371687 FOREIGN KEY (NDSID) REFERENCES NDS (ID);
ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo917205; 
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo917205 FOREIGN KEY (ContractStateID) REFERENCES ContractState (ID);
ALTER TABLE ContractDoc DROP CONSTRAINT FKContractDo906594; 
ALTER TABLE ContractDoc ADD CONSTRAINT FKContractDo906594 FOREIGN KEY (ContractorID) REFERENCES Contractor (ID);
ALTER TABLE Contractdoc_Funds_Fact DROP CONSTRAINT FKContractdo229014;
ALTER TABLE Contractdoc_Funds_Fact ADD CONSTRAINT FKContractdo229014 FOREIGN KEY (ContractdocID) REFERENCES ContractDoc (ID) ON DELETE CASCADE;
ALTER TABLE Contractdoc_Funds_Fact DROP CONSTRAINT FKContractdo589247; 
ALTER TABLE Contractdoc_Funds_Fact ADD CONSTRAINT FKContractdo589247 FOREIGN KEY (Time_DimID) REFERENCES Time_Dim (ID) ON DELETE CASCADE;
ALTER TABLE Contractor DROP CONSTRAINT FKContractor394676;
ALTER TABLE Contractor ADD CONSTRAINT FKContractor394676 FOREIGN KEY (ContractorTypeID) REFERENCES ContractorType (ID);
ALTER TABLE ContractorAuthority DROP CONSTRAINT FKContractor191604;
ALTER TABLE ContractorAuthority ADD CONSTRAINT FKContractor191604 FOREIGN KEY (AuthorityID) REFERENCES Authority (ID);
ALTER TABLE ContractTranActDoc DROP CONSTRAINT FKContractTr647138;
ALTER TABLE ContractTranActDoc ADD CONSTRAINT FKContractTr647138 FOREIGN KEY (ActID) REFERENCES Act (ID) ON DELETE CASCADE;
ALTER TABLE EfParameterStageResult DROP CONSTRAINT FKEfParamete714975; 
ALTER TABLE EfParameterStageResult ADD CONSTRAINT FKEfParamete714975 FOREIGN KEY (EconomEfficiencyParameterID) REFERENCES EconomEfficiencyParameter (ID);
ALTER TABLE EnterpriseAuthority DROP CONSTRAINT FKEnterprise947996;
ALTER TABLE EnterpriseAuthority ADD CONSTRAINT FKEnterprise947996 FOREIGN KEY (EmployeeID) REFERENCES Employee (ID) ON DELETE CASCADE;
ALTER TABLE FunctionalCustomer DROP CONSTRAINT FKFunctional524086;
ALTER TABLE FunctionalCustomer ADD CONSTRAINT FKFunctional524086 FOREIGN KEY (FunctionalCustomerTypeID) REFERENCES FunctionalCustomerType (ID);
ALTER TABLE IMPORTINGSCHEMEITEM DROP CONSTRAINT FKIMPORTINGS434803;
ALTER TABLE IMPORTINGSCHEMEITEM ADD CONSTRAINT FKIMPORTINGS434803 FOREIGN KEY (SchemeID) REFERENCES IMPORTINGSCHEME (ID) ON DELETE CASCADE;
ALTER TABLE Person DROP CONSTRAINT FKPerson162299;
ALTER TABLE Person ADD CONSTRAINT FKPerson162299 FOREIGN KEY (DegreeID) REFERENCES Degree (ID);
ALTER TABLE Person DROP CONSTRAINT FKPerson487057;
ALTER TABLE Person ADD CONSTRAINT FKPerson487057 FOREIGN KEY (ContractorPositionID) REFERENCES ContractorPosition (ID);
ALTER TABLE Report_FilterState DROP CONSTRAINT FKReport_Fil356408;
ALTER TABLE Report_FilterState ADD CONSTRAINT FKReport_Fil356408 FOREIGN KEY (ReportID) REFERENCES Report (ID) ON DELETE CASCADE;
ALTER TABLE Report_FilterState DROP CONSTRAINT FKReport_Fil878991;
ALTER TABLE Report_FilterState ADD CONSTRAINT FKReport_Fil878991 FOREIGN KEY (FilterStateID) REFERENCES FilterState (ID) ON DELETE CASCADE;
ALTER TABLE ReportGrouping DROP CONSTRAINT ContractTypeGroup_FK;
ALTER TABLE ReportGrouping ADD CONSTRAINT ContractTypeGroup_FK FOREIGN KEY (ContractTypeID) REFERENCES ContractType (ID) ON DELETE CASCADE;
ALTER TABLE ReportGrouping DROP CONSTRAINT ContracttypeSubgroup_FK;
ALTER TABLE ReportGrouping ADD CONSTRAINT ContracttypeSubgroup_FK FOREIGN KEY (ContractTypeSubgroupID) REFERENCES ContractType (ID) ON DELETE CASCADE;
ALTER TABLE Responsible DROP CONSTRAINT ContractdocResponsible_FK;
ALTER TABLE Responsible ADD CONSTRAINT ContractdocResponsible_FK FOREIGN KEY (ContractdocID) REFERENCES ContractDoc (ID) ON DELETE CASCADE;
ALTER TABLE Responsible DROP CONSTRAINT StageResponsible_FK;
ALTER TABLE Responsible ADD CONSTRAINT StageResponsible_FK FOREIGN KEY (StageID) REFERENCES Stage (ID) ON DELETE CASCADE;
ALTER TABLE Schedule DROP CONSTRAINT FKSchedule996822;
ALTER TABLE Schedule ADD CONSTRAINT FKSchedule996822 FOREIGN KEY (WorkTypeID) REFERENCES WorkType (ID);
ALTER TABLE Schedule DROP CONSTRAINT FKSchedule245187; 
ALTER TABLE Schedule ADD CONSTRAINT FKSchedule245187 FOREIGN KEY (CurrencyMeasureID) REFERENCES CurrencyMeasure (ID);
ALTER TABLE Stage DROP CONSTRAINT FKStage472417;
ALTER TABLE Stage ADD CONSTRAINT FKStage472417 FOREIGN KEY (NdsAlgorithmID) REFERENCES NDSAlgorithm (ID);
ALTER TABLE Stage DROP CONSTRAINT AprovalStageState_FK;
ALTER TABLE Stage ADD CONSTRAINT AprovalStageState_FK FOREIGN KEY (ApprovalStateID) REFERENCES ApprovalState (ID);
ALTER TABLE StageResult DROP CONSTRAINT FKStageResul865700;
ALTER TABLE StageResult ADD CONSTRAINT FKStageResul865700 FOREIGN KEY (NTPSubViewID) REFERENCES NTPSubView (ID);
ALTER TABLE StageResult DROP CONSTRAINT FKStageResul506505;
ALTER TABLE StageResult ADD CONSTRAINT FKStageResul506505 FOREIGN KEY (EconomicEfficiencyTypeID) REFERENCES EconomEfficiencyType (ID);




















