/* 
	UPDATE TO 1.0.0.23
*/

ALTER TABLE Stage MODIFY Subject NVARCHAR2(2000);


UPDATE Act SET SignDate=CURRENT_DATE WHERE SignDate IS NULL; 
UPDATE Act SET TotalSum=0 WHERE TotalSum IS NULL;
UPDATE Act SET Sumfortransfer=0 WHERE Sumfortransfer IS NULL;
UPDATE Act SET NdsalgorithmID=1 WHERE NdsalgorithmID IS NULL;
UPDATE Act SET CurrencyID=1 WHERE CurrencyID IS NULL;
UPDATE Act SET CurrencymeasureID=1 WHERE CurrencymeasureID IS NULL;


ALTER TABLE Act MODIFY TotalSum NUMBER(18,2) NOT NULL;
ALTER TABLE Act MODIFY SignDate DATE NOT NULL;
ALTER TABLE Act MODIFY RegionID NUMBER(10) NULL;
ALTER TABLE Act MODIFY EnterpriceAuthorityID NUMBER(10);
ALTER TABLE Act MODIFY NdsalgorithmID NUMBER(10) NOT NULL;
ALTER TABLE Act MODIFY CurrencyID NUMBER(10) NOT NULL;
ALTER TABLE Act MODIFY CurrencymeasureID NUMBER(10) NOT NULL;
ALTER TABLE Act MODIFY Sumfortransfer NUMBER(18,2) NOT NULL;