/*
      UPDATE TO 1.0.0.11      
*/
ALTER TABLE StageResult DROP CONSTRAINT FKStageResul876631;
ALTER TABLE NTPSubView DROP CONSTRAINT FKNTPSubView475996;
ALTER TABLE StageResult DROP CONSTRAINT FKStageResul865700;
ALTER TABLE StageResult DROP CONSTRAINT FKStageResul506505;
ALTER TABLE EfficienceParameterType DROP CONSTRAINT FKEfficience269842;
ALTER TABLE EfficienceParameterType DROP CONSTRAINT FKEfficience747914;
ALTER TABLE EfParameterStageResult DROP CONSTRAINT FKEfParamete714975;
ALTER TABLE EfParameterStageResult DROP CONSTRAINT FKEfParamete943607;

ALTER TABLE StageResult ADD CONSTRAINT FKStageResul876631 FOREIGN KEY (StageID) REFERENCES Stage (ID) ON DELETE Cascade;
ALTER TABLE NTPSubView ADD CONSTRAINT FKNTPSubView475996 FOREIGN KEY (NTPViewID) REFERENCES NTPView (ID) ON DELETE Cascade;
ALTER TABLE StageResult ADD CONSTRAINT FKStageResul865700 FOREIGN KEY (NTPSubViewID) REFERENCES NTPSubView (ID) ON DELETE Cascade;
ALTER TABLE StageResult ADD CONSTRAINT FKStageResul506505 FOREIGN KEY (EconomicEfficiencyTypeID) REFERENCES EconomEfficiencyType (ID) ON DELETE Cascade;
ALTER TABLE EfficienceParameterType ADD CONSTRAINT FKEfficience269842 FOREIGN KEY (EconomEfficiencyParameterID) REFERENCES EconomEfficiencyParameter (ID) ON DELETE Cascade;
ALTER TABLE EfficienceParameterType ADD CONSTRAINT FKEfficience747914 FOREIGN KEY (EconomEfficiencyTypeID) REFERENCES EconomEfficiencyType (ID) ON DELETE Cascade;
ALTER TABLE EfParameterStageResult ADD CONSTRAINT FKEfParamete714975 FOREIGN KEY (EconomEfficiencyParameterID) REFERENCES EconomEfficiencyParameter (ID) ON DELETE Cascade;
ALTER TABLE EfParameterStageResult ADD CONSTRAINT FKEfParamete943607 FOREIGN KEY (StageResultID) REFERENCES StageResult (ID) ON DELETE Cascade;

