//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.261
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCDomain {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCDomain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appliedat.
        /// </summary>
        internal static string Contractdoc_this_Appliedat {
            get {
                return ResourceManager.GetString("Contractdoc_this_Appliedat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Contractdoc_this_appliedat_less_startat_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_appliedat_less_startat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Approvedat.
        /// </summary>
        internal static string Contractdoc_this_Approvedat {
            get {
                return ResourceManager.GetString("Contractdoc_this_Approvedat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата подписания договора должна быть между датами начала и окончания договора.
        /// </summary>
        internal static string Contractdoc_this_approvedat_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_approvedat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contractor.
        /// </summary>
        internal static string Contractdoc_this_Contractor {
            get {
                return ResourceManager.GetString("Contractdoc_this_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contractstate.
        /// </summary>
        internal static string Contractdoc_this_Contractstate {
            get {
                return ResourceManager.GetString("Contractdoc_this_Contractstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договор должен находится в состоянии подписан, если задана дата подписания.
        /// </summary>
        internal static string Contractdoc_this_Contractstate_mastbe_signed_if_approved_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_Contractstate_mastbe_signed_if_approved_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contracttype.
        /// </summary>
        internal static string Contractdoc_this_Contracttype {
            get {
                return ResourceManager.GetString("Contractdoc_this_Contracttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        internal static string Contractdoc_this_Currency {
            get {
                return ResourceManager.GetString("Contractdoc_this_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения цены и валюта должны быть заданы.
        /// </summary>
        internal static string Contractdoc_this_currency_and_measure_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_currency_and_measure_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currencymeasure.
        /// </summary>
        internal static string Contractdoc_this_Currencymeasure {
            get {
                return ResourceManager.GetString("Contractdoc_this_Currencymeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currencyrate.
        /// </summary>
        internal static string Contractdoc_this_Currencyrate {
            get {
                return ResourceManager.GetString("Contractdoc_this_Currencyrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это поле является обязательным для заполнения..
        /// </summary>
        internal static string Contractdoc_this_data_mustbe_specified {
            get {
                return ResourceManager.GetString("Contractdoc_this_data_mustbe_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disposal.
        /// </summary>
        internal static string Contractdoc_this_Disposal {
            get {
                return ResourceManager.GetString("Contractdoc_this_Disposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Endsat.
        /// </summary>
        internal static string Contractdoc_this_Endsat {
            get {
                return ResourceManager.GetString("Contractdoc_this_Endsat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала должна быть меньше даты окончания.
        /// </summary>
        internal static string Contractdoc_this_endsat_less_startat_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_endsat_less_startat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для договора в иностранной валюте требуется курс.
        /// </summary>
        internal static string Contractdoc_this_foreign_currency_rate_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_foreign_currency_rate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internalnum.
        /// </summary>
        internal static string Contractdoc_this_Internalnum {
            get {
                return ResourceManager.GetString("Contractdoc_this_Internalnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nds.
        /// </summary>
        internal static string Contractdoc_this_Nds {
            get {
                return ResourceManager.GetString("Contractdoc_this_Nds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ndsalgorithm.
        /// </summary>
        internal static string Contractdoc_this_Ndsalgorithm {
            get {
                return ResourceManager.GetString("Contractdoc_this_Ndsalgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контрагент договора должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_contractor_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_contractor_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние подписания договора должно быть задано.
        /// </summary>
        internal static string Contractdoc_this_no_contractstate_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_contractstate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип договора должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_contracttype_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_contracttype_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта договора должена быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_currency_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_currency_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основание договора должено быть указано.
        /// </summary>
        internal static string Contractdoc_this_no_disposal_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_disposal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания выполнения работ должна быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_endsat_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_endsat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер договора должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_internalnum_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_internalnum_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица измерения валюты договора должена быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_measure_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_measure_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгоритм НДС должн быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_nds_algorithm_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_nds_algorithm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставка НДС должна быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_nds_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_nds_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководитель договора должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_person_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_person_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгоритм НДС аванса должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_prepayment_nds_algorithm_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_prepayment_nds_algorithm_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена договора должна быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_price_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_price_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для договоров в иностранной валюте должны быть указаны курс и дата курса.
        /// </summary>
        internal static string Contractdoc_this_no_rate_and_ratedate_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_rate_and_ratedate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала выполнения работ должна быть указана.
        /// </summary>
        internal static string Contractdoc_this_no_startat_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_startat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предмет договора должен быть указан.
        /// </summary>
        internal static string Contractdoc_this_no_subject_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_no_subject_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это поле является обязательным для заполнения..
        /// </summary>
        internal static string Contractdoc_this_not_nullable_field_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_not_nullable_field_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Person.
        /// </summary>
        internal static string Contractdoc_this_Person {
            get {
                return ResourceManager.GetString("Contractdoc_this_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма аванса не может быть больше цены договора.
        /// </summary>
        internal static string Contractdoc_this_prepayment_sum_must_not_exceed_total_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_prepayment_sum_must_not_exceed_total_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prepaymentndsalgorithm.
        /// </summary>
        internal static string Contractdoc_this_Prepaymentndsalgorithm {
            get {
                return ResourceManager.GetString("Contractdoc_this_Prepaymentndsalgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prepaymentpercent.
        /// </summary>
        internal static string Contractdoc_this_Prepaymentpercent {
            get {
                return ResourceManager.GetString("Contractdoc_this_Prepaymentpercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма авансов по годам должна быть равна общей сумме по годам.
        /// </summary>
        internal static string Contractdoc_this_prepayments_not_equals_total_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_prepayments_not_equals_total_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prepaymentsum.
        /// </summary>
        internal static string Contractdoc_this_Prepaymentsum {
            get {
                return ResourceManager.GetString("Contractdoc_this_Prepaymentsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string Contractdoc_this_Price {
            get {
                return ResourceManager.GetString("Contractdoc_this_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ratedate.
        /// </summary>
        internal static string Contractdoc_this_Ratedate {
            get {
                return ResourceManager.GetString("Contractdoc_this_Ratedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для подписанного договора должна быть задана дата подписания.
        /// </summary>
        internal static string Contractdoc_this_sign_date_error {
            get {
                return ResourceManager.GetString("Contractdoc_this_sign_date_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Startat.
        /// </summary>
        internal static string Contractdoc_this_Startat {
            get {
                return ResourceManager.GetString("Contractdoc_this_Startat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject.
        /// </summary>
        internal static string Contractdoc_this_Subject {
            get {
                return ResourceManager.GetString("Contractdoc_this_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер начального столбца области данных должен быть меньше номера конечного.
        /// </summary>
        internal static string Importer_this_Region_bound_column_values_error {
            get {
                return ResourceManager.GetString("Importer_this_Region_bound_column_values_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер начальной строки области данных должен быть меньше номера конечной.
        /// </summary>
        internal static string Importer_this_Region_bound_row_values_error {
            get {
                return ResourceManager.GetString("Importer_this_Region_bound_row_values_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент аванса должен быть числом от 0 до 100..
        /// </summary>
        internal static string PrepaymentDataErrorHandler_HandlePrepaymentError_PrepaymentPercentMustNotExceed0or100 {
            get {
                return ResourceManager.GetString("PrepaymentDataErrorHandler_HandlePrepaymentError_PrepaymentPercentMustNotExceed0o" +
                        "r100", resourceCulture);
            }
        }
    }
}
