-- ****** Object: Table Trigger UD.CONTRACTHIERARCHY_PRECALCS Script Date: 04.11.2011 18:31:44 ******
CREATE OR REPLACE TRIGGER "CONTRACTHIERARCHY_PRECALCS"
  AFTER
  UPDATE OF "GENERALCONTRACTDOCID", "SUBCONTRACTDOCID" OR DELETE OR INSERT
  ON "CONTRACTHIERARCHY"
BEGIN  	

END;
